apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-api-service
spec:
  type: LoadBalancer
  selector:
    app: weatherforecast-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
