apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
      sigV4Auth: false
      sigV4AuthWithAccessKey: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
      sigV4AccessKey: ""
      sigV4SecretKey: ""
      sigV4Region: ""
    version: 1
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: ""
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    jsonData:
      esVersion: 70
      timeField: "@timestamp"
      interval: Daily
    secureJsonData:
      password: ""
    version: 1
    readOnly: true
